### ISSUE TITLE
Support generation of multiple MIO config files

### ISSUE THREAD

**Issue by u-u-h** [Seagate/cortx-motr-apps#38]
`c0appzrcgen` and `motraddr.sh` should support generating multiple config files for MIO in one call. Suggested usage:

`motradd.sh --mio 3 config1 config21 config42`

to obtain 3 different configs under the specified file names.

**Comment by nezzzu** [comment]
@u-u-h , This is now implemented and available on the SAGE cluster. Please check, and let me know if this works as you expected.
```
umanesan1@client-24~[1001]motraddr.sh --mio 3 a.txt b.txt
Illeg number of arguments!
umanesan1@client-24~[1002]motraddr.sh --mio 3 a.txt b.txt c.txt
umanesan1@client-24~[1005]cat a.txt b.txt c.txt | grep INST
  MOTR_INST_ADDR: 172.18.1.24@o2ib:12345:4:1
  MOTR_INST_ADDR: 172.18.1.24@o2ib:12345:4:2
  MOTR_INST_ADDR: 172.18.1.24@o2ib:12345:4:3
umanesan1@client-24~[1006]

```

**Comment by u-u-h** [comment]
@nezzzu This is not available on all clients, is it? I failed to find it on -21 for instance.

**Comment by u-u-h** [comment]
Seems to work on sage, startup time of mio is really long though.

**Comment by nezzzu** [comment]
@u-u-h , do you mean the mio_init() taking approximately 40sec on Sage? We are working on fixing it.

**Comment by u-u-h** [comment]
Yes. I didn't time it, just thought it was very long.

**Comment by nezzzu** [comment]
Thanks for the confirmation. Yes, the clovis_init() function (now called m0client_init) takes a lot of time to complete. This affect all motr apps on Sage. Working on fixing it. Thanks.

**Comment by hessio** [comment]
Hi @u-u-h and @nezzzu is this issue resolved? It seems that this issue can be closed as SAGE is now over? Is this issue still relevant?

**Comment by u-u-h** [comment]
The issue of slow startup (#41) is still not solved as far as I can see (it's better, but not good).
Generating multiple configurations worked on sage; I have not checked if the upstream version on a system other than sage though.

**Comment by hessio** [comment]
Ok I will label this issue as backlog as I know there was work being done on this issue.

**Comment by chandradharraval** [comment]
@u-u-h , @hessio - Is this still valid issue?

**Comment by cortx-admin** [comment]
> Chandradhar Raval commented in Jira Server:

Marking this JIRA Closed as per confirmation from [~519680]
