### ISSUE TITLE
Improve startup time of motr applications (MIO in particular)

### ISSUE THREAD

**Issue by u-u-h** [Seagate/cortx-motr-apps#41]
The MIO startup (https://github.com/Seagate/cortx-mio `mio_init()`) is very slow, e.g., on the sage system. 40s are not unusual.

For user code connecting to MIO this is unacceptable, both because the application may have a shorter runtime than that altogether, and because the MIO init is blocking (rightly so), so startup delay accumulates with other initializations that may be done. (Note that I'm not suggesting to make it non-blocking; this would only rarely solve the issue, and complicate user code which then cannot rely on MIO being ready.)

**Comment by u-u-h** [comment]
^^ @nezzzu maybe?

**Comment by nezzzu** [comment]
@truptiatseagate @andriytk This is the same clovis_init() or m0client_init() that is causing the delay in mio_init(). What is the current status of the fix? When can we expect the fix to be available in the main branch?

**Comment by andriytk** [comment]
@nezzzu see here - https://github.com/Seagate/cortx-hare/pull/1737.

**Comment by hessio** [comment]
Is it ok to close this issue now based on this PR https://github.com/Seagate/cortx-hare/pull/1780

**Comment by andriytk** [comment]
No, not yet. The mentioned PR improves the situation - yes, but it does not fix the problem entirely.

Also, we had to decrease the number of client slots per client node in the cluster from 16 to 4 to further decrease the startup delay, which is 4 secs now. But it should be less than 1 sec.

**Comment by hessio** [comment]
ok thanks for the update

**Comment by chandradharraval** [comment]
@andriytk - Do we still see this issue?

**Comment by chandradharraval** [comment]
@u-u-h , @andriytk - Is this still valid issue?

**Comment by u-u-h** [comment]
I can't test with current versions since the cluster we used has been dismantled. @nezzzu may be able to comment on this, he could reproduce it, and may have access to a current motr installation.

**Comment by chandradharraval** [comment]
Hi @nezzzu,
Is this still reproducible?

**Comment by cortx-admin** [comment]
> ganesan umanesan commented in Jira Server:

[~530903] The Sage cluster is in the process of being set up as part of the IOSEA project. It is estimated to be back online by October end. I will verify the startup time again once the cluster becomes available.

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
