### ISSUE TITLE
sscanf() without field width limits can crash with huge input data.

### ISSUE THREAD

**Issue by johnbent** [Seagate/cortx-motr-apps#94]
#### Occurred on:
+ **Commit**:  9f3a3aad952bccbac9a46afcf277bb5194463c1e
+ **File**:    [c0appz.c](https://github.com/Seagate/cortx-motr-apps/blob/9f3a3aad952bccbac9a46afcf277bb5194463c1e/c0appz.c)
+ **LineNum**: [150](https://github.com/Seagate/cortx-motr-apps/blob/9f3a3aad952bccbac9a46afcf277bb5194463c1e/c0appz.c#L150)
+ **Code**:    `if (sscanf(s, " %[#\n\r]", p->name))`

    
#### Currently on:
+ **Commit**:  c5b8ea130ac4401873e12de47218f9d8a62f6016
+ **File**:    [c0appz.c](https://github.com/Seagate/cortx-motr-apps/blob/c5b8ea130ac4401873e12de47218f9d8a62f6016/c0appz.c)
+ **LineNum**: [153](https://github.com/Seagate/cortx-motr-apps/blob/c5b8ea130ac4401873e12de47218f9d8a62f6016/c0appz.c#L153)

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-31316. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by nezzzu** [comment]
@andriytk There is no snscanf(). How can we fix this for Codacy?

**Comment by andriytk** [comment]
This can be safely ignored here. The length of the string s is guaranteed by `fgets(s, MAX_CONF_STR_LEN, in)` to be not greater than `MAX_CONF_STR_LEN`.

**Comment by nezzzu** [comment]
I will add sscanf() to the exception list. Closing this issue.

**Comment by cortx-admin** [comment]
> Chandradhar Raval commented in Jira Server:

Marking this issue Closed and corresponding Github is closed
